### ISSUE TITLE
Incorrect error message when the grakn server is not started

### ISSUE THREAD

**Issue by VladGan** [graknlabs/console#106] opened 2021-01-14 13:03 UTC
## Description

When the Grakn server is not started and the user tries to run the command `databse list` in console, instead of showing a clear and understandable exception, the console prints an 
```io exception```
 message.

The same may be the case for the rest of the commands, but not tested.

## Expected Output

The message should indicate that the server is not started.

**Comment by lriuui0x0** [comment] 2021-01-14 13:06
@VladGan Please can you work on this bug? It's likely that client-java is not throwing the right exception.

**Comment by vmax** [comment] 2021-01-25 10:11
Duplicate of #108 which is already fixed

**Closed by vmax** 2021-01-25 10:11 UTC
Labels: priority: low, type: bug
